### ISSUE TITLE
Nuxt integration docs

### ISSUE THREAD

**Issue by FluksikartonGOD** [hmsk/frontmatter-markdown-loader#1]
Please can you add some documentation for integrating with [Nuxt ](https://nuxtjs.org/)1 and 2. Thanks!

**Comment by hmsk** [comment]
Hi, I'm not going to put about Nuxt to the doc specifically. Since it's nothing special even for Nuxt.

In`nuxt.config.js`, you can configure the loader like:

```js
build: {
  ...
  extend (config, { isDev, isClient }) {
    ...
    config.module.rules.push({
      test: /\.md$/,
      loader: 'frontmatter-markdown-loader',
      include: path.resolve(__dirname, 'contents'),
      options: {
        vue: {
          root: "dynamicMarkdown"
        }
      }
    }
    ...
  }
  ...
}
```

then, you can place markdown files into `/contents` and import :)

**Comment by FluksikartonGOD** [comment]
Really thanks couldnt find it out myself anyway dont see a reason not to
add it

На сб, 6.10.2018 г., 11:00 Kengo Hamasaki <notifications@github.com> написа:
