### ISSUE TITLE
MD Vue Component with Nuxt asyncData

### ISSUE THREAD

**Issue by luklus** [hmsk/frontmatter-markdown-loader#105]
```js
<template>
  <div>
    <h1>Hello</h1>

    <client-only>
      <component :is="dynamicComponent" />
    </client-only>
  </div>
</template>

<script>
export default {
  name: 'PostPage',
  async asyncData({ params }) {
    const file = await import(`~/blog/${params.post}.md`)

    return {
      text: file.attributes.text,
      dynamicComponent: file.vue.component
    }
  }
}
</script>
```

causes a problem:

RangeError
Maximum call stack size exceeded 

Terminal:
WARN  Cannot stringify a function data                                                                    
WARN  Cannot stringify a function render                                                                    
WARN  Cannot stringify a function created                                                                    
WARN  Cannot stringify a function VueComponent

Are there any restrictions with Nuxt asyncData?

**Comment by hmsk** [comment]
`asyncData` on Nuxt supports only primitives.
If you're eager to process through `asyncData`, use `vue.render` , `vue.staticRenderFns`.

This thread may help you: https://github.com/hmsk/frontmatter-markdown-loader/issues/83#issuecomment-552101546
