### ISSUE TITLE
Passing data from frontmatter to component inside markdown

### ISSUE THREAD

**Issue by J4VMC** [hmsk/frontmatter-markdown-loader#112]
Hello,

I'm trying to access frontmatter attributes in a component rendered inside a Markdown page, but I'm having no luck so far. The setup I have is as follows:

`nuxt.config.js`
```
      config.module.rules.push({
        test: /\.md$/,
        include: resolve(__dirname, 'content'),
        loader: 'frontmatter-markdown-loader',
        options: {
          mode: [Mode.HTML, Mode.VUE_COMPONENT],
          vue: {
            root: 'dynamicMarkdown'
          }
        }
      });
```

`contents/posts/post-1.md`
```
---
images: [/blog/detail-1.jpg, /blog/detail-2.jpg]

---

This is a demo post with markdown.

<ImageGallery :images="images" /> // These should be the images from the frontmatter above but they don't show.

This is more content.
```

`components/DynamicMarkdown.vue`
```
<template>
  <div>
    <div v-html="content"></div>
  </div>
</template>

<script>
export default {
  name: 'DynamicMarkdown',
  props: {
    content: {
      type: String,
      default() {}
    },
    images: {
      type: Array,
      default() {}
    }
  }
};
</script>
```

`components/ImageGallery.vue`
```
<template>
  <v-container>
    <v-row>
      <v-col v-for="image in images" :key="image" :md="mdCols" cols="12" sm="6">
        <img
          :data-src="require('assets/images' + image)"
          :data-srcset="require('assets/images' + image).srcSet"
          alt="Image"
          sizes="(max-width: 600) 576px, (min-width: 601) and (max-width: 1263) 426px, (min-width: 1264) 272.25px"
          class="lazyload page-image"
        />
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
export default {
  name: 'ImageGallery',
  props: {
    images: {
      type: Array,
      default() {}
    }
  },
  computed: {
    mdCols() {
      switch (this.props.images.length) {
        case 2:
          return 6;
        case 3:
          return 4;
        case 4:
          return 3;
        default:
          return 12;
      }
    }
  }
};
</script>

<style scoped></style>
```

`pages/_slug.vue`
```
<template>
  <div>
    <v-container>
      <v-row>
        <v-col>
            <DynamicMarkdown :content="contentHtml" :images="images" />
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>
<script>
import DynamicMarkdown from '~/components/DynamicMarkdown';

export default {
  name: 'BlogArticle',
  components: {
    DynamicMarkdown
  },
  async asyncData({ params }) {
    try {
      const post = await import(`~/content/posts/${params.slug}.md`);
      return {
        title: post.attributes.title,
        contentDate: post.attributes.date,
        images: post.attributes.images,
        contentHtml: post.html
      };
    } catch (err) {
      return false;
    }
  }
};
</script>

```

Would you be able to tell me how to achieve this?

**Comment by hmsk** [comment]
It's not supported but interesting idea. I may support that usage at some point.
At this time, if you need to pass something to the custom element (Vue components), give JS primitives directly (or plain text without `v-bind` / `:`)

```html
<ImageGallery :images="['/blog/detail-1.jpg','/blog/detail-2.jpg']" />
```

works for instance.

Just a thing I noticed by reading your code:
`DynamicMarkdown` doesn't run `ImageGallery` component even if you don't give `:images` props.
Since `DyamicMarkdown` is just rendering HTML which is passed through `:content` 😉 

To inject `ImageGallery`, these links may help you:
- https://hmsk.github.io/frontmatter-markdown-loader/vue.html#c-inject-other-components
- https://github.com/hmsk/frontmatter-markdown-loader-nuxt-sample

**Comment by J4VMC** [comment]
Hi

Thanks for the reply. It'd be a very good feature for the feature I think, as it'd open up a few more possibilities.

I tried following those links, but I use `async data` to import my posts in my `_slug.vue` page and I can't figure out how to combine that and what's explained in your links.

```
<script>
import DynamicMarkdown from '~/components/BaseMarkdownContent';

export default {
  name: 'BlogArticle',
  components: {
    DynamicMarkdown,
  },
  async asyncData({ params }) {
    try {
      const post = await import(`~/content/posts/${params.slug}.md`);
      return {
        title: post.attributes.title,
        contentDate: post.attributes.date,
        image: post.attributes.image,
        author: post.attributes.author,
        tags: post.attributes.tags,
        short: post.attributes.short,
        slug: post.attributes.slug,
        contentType: post.attributes.type,
        contentHtml: post.html
      };
    } catch (err) {
      return false;
    }
  },
//more code here
```

Would it be possible at all?

**Comment by hmsk** [comment]
`asyncData` in Nuxt supports only JS primitives. You need to import markdown file in another way.
https://github.com/hmsk/frontmatter-markdown-loader/issues/83#issuecomment-552101546

**Comment by J4VMC** [comment]
> To inject `ImageGallery`, these links may help you:
> 
> * https://hmsk.github.io/frontmatter-markdown-loader/vue.html#c-inject-other-components
> * https://github.com/hmsk/frontmatter-markdown-loader-nuxt-sample

I keep getting `Cannot read property 'images' of undefined` when accessing the page, even thought `BaseImageGallery` is registered as a Global Component.

In my `/blog/_slug.vue` I have the following:
```
const BaseImageGallery = () => import('~/components/BaseImageGallery');
export default {
  data() {
    return {
      DynamicContent: null
    };
  },
  created() {
    const post = require(`~/content/services/${this.$route.params.slug}.md`);
    this.DynamicContent = {
      extends: post.vue.component,
      components: { BaseImageGallery }
    };
  },
```

`/content/blog/post-1.vue`
```
---
images: [/blog/detail-1.jpg, /blog/detail-2.jpg]

---

This is a demo post with markdown.

<BaseImageGallery :images="['/blog/detail-1.jpg','/blog/detail-2.jpg']" />

This is more content.
```

Is this correct or am I missing something else to make it work? Thanks for the help.

**Comment by hmsk** [comment]
I may help if you provide a reproducible repository. Can't figure out your problem from only codes you pasted.

**Comment by J4VMC** [comment]
> I may help if you provide a reproducible repository. Can't figure out your problem from only codes you pasted.

I can give you access to it, but it's a private repo. The cod

**Comment by J4VMC** [comment]
I've created this CodePen project with the exact same code I've got for the Markdown part

https://codepen.io/J4VMC/project/editor/AMmMgw
