### ISSUE TITLE
React version can't handle images

### ISSUE THREAD

**Issue by AlexGilleran** [hmsk/frontmatter-markdown-loader#114]
Markdown like this:

```
![Natural Healing Team](/static/Natural-Healing-team.jpg "Natural Healing Team")
```

Will result in this error:

```
./content/about-us.md
SyntaxError: unknown: Expected corresponding JSX closing tag for <img> (5:103)

  3 |           <div>
  4 |             <h1>About Us</h1>
> 5 | <p><img src="/static/Natural-Healing-team.jpg" alt="Natural Healing Team" title="Natural Healing Team"></p>
```

The code looks like it drops the HTML output of frontmatter directly into a react component, so I'm not sure how it's even possible to work around this (except for directly using HTML for images). I guess you'd have to go through the generated HTML and fix all the unclosed tags before letting React interpret it? :(

**Comment by hmsk** [comment]
Thanks for your report! This is the bug, JSX is expecting self-closing tag for `img`. I'm going to fix this problem next week.

As the quick workaround, you can configure markdown compiler like (`xhtmlOut` gives self-closing tag):

```js
{
  test: /\.md$/,
  loader: 'frontmatter-markdown-loader'
  options: {
    markdownIt: {
      html: true,
      xhtmlOut: true
    }
  }
}
```

**Comment by hmsk** [comment]
Delivered as [3.2.0](https://github.com/hmsk/frontmatter-markdown-loader/releases/tag/v3.2.0) 😉
