### ISSUE TITLE
Access attributes etc

### ISSUE THREAD

**Issue by soniktrooth** [hmsk/frontmatter-markdown-loader#12]
I'm having trouble accessing any of the properties after importing md files. 

Here's my code:
`nuxt.config.js`
```
{
  test: /\.md$/,
  loader: 'frontmatter-markdown-loader'
}
```

`component.vue`
```
import md from '~/content/events/my-markdown-file.md'
```

In this case `md` is the correctly rendered markup from the md file but `md.attributes`, `md.body` and `md.html` are all undefined. 

What am I doing wrong?

**Comment by soniktrooth** [comment]
@hmsk thanks for the reply. I realized that I was still including the `'@nuxtjs/markdownit'` module which, as you said, was why it was getting converted to markdown. However after removing that and replacing it with your module I get 
```TypeError: string.split is not a function   ```
My repo is here if you have a chance to look: https://github.com/soniktrooth/c3v

Thanks!

**Comment by hmsk** [comment]
> TypeError: string.split is not a function

I didn't see such the error but found the config is not loading the loader for the server build.

```diff
diff --git a/nuxt.config.js b/nuxt.config.js
index 79ac395..35d4b4d 100644
--- a/nuxt.config.js
+++ b/nuxt.config.js
@@ -105,14 +105,16 @@ module.exports = {
             test: /\.(js|vue)$/,
             loader: 'eslint-loader',
             exclude: /(node_modules)/
-          },
-          {
-            test: /\.md$/,
-            loader: 'frontmatter-markdown-loader',
-            include: path.resolve(__dirname, 'content')
           }
         )
       }
+      config.module.rules.push(
+        {
+          test: /\.md$/,
+          loader: 'frontmatter-markdown-loader',
+          include: path.resolve(__dirname, 'content')
+        }
+      )
     }
   }
 }
```

here's what you expect in your current HEAD:

![image](https://user-images.githubusercontent.com/85887/52161755-f3d3f580-267e-11e9-961c-10bf97c9a3ec.png)

So, there's not any problem in the loader at all. let me close this issue 😉

**Comment by soniktrooth** [comment]
Thank you so much, I didn't notice this!
