### ISSUE TITLE
Pure date gets parsed into UTC timestamp

### ISSUE THREAD

**Issue by lobo-tuerto** [hmsk/frontmatter-markdown-loader#134]
I'm having an issue where my frontmatter contains an attribute that's a pure date, for example:

```yaml
date: 2019-08-31T12:00:00-06:00
last_update: 2020-04-04
```

Here `date` is converted OK, as expected, into an ISO8601 timestamp, but the `last_update` date, instead of being converted into an ISO8601 date it gets converted into a full timestamp.

```js
date: "2019-08-31T18:00:00.000Z"
last_update: "2020-04-04T00:00:00.000Z"
```

Is there anyway to tweak this behavior?
Ideally the output I'd be looking for is to have this:

```js
date: "2019-08-31T18:00:00.000Z"
last_update: "2020-04-04"
```

Given a timestamp, receive a timestamp.
Given a pure date, receive a pure date.

(I know I can define `last_update` as `"2020-04-04"` but I'd like to avoid having to put quotes around the date in the frontmatter.)

**Comment by hmsk** [comment]
Thanks for your feedback.

This won't be supported. FML is relying on `js-yaml` through `front-matter`. `js-yaml` believes the timestamp type of the original repo of YAML. https://yaml.org/type/timestamp.html
