### ISSUE TITLE
How can we access the markdown attributes right from nuxt.config.js?

### ISSUE THREAD

**Issue by heriisei** [hmsk/frontmatter-markdown-loader#135]
I need to create filter function in order to build sitemap from dynamic article routes. The filter function will work to filtering out published article by read the status attributes inside each markdown files.

_The problem is I cannot find the right way to access & iterate each markdown attributes directly from nuxt.config.js._

Because of I'm use this repo [brevifolia-nuxt-forestry](https://github.com/kendallstrautman/brevifolia-nuxt-forestry) as my project base. I've try to create function by modified the default [nuxt.config.js](https://github.com/kendallstrautman/brevifolia-nuxt-forestry/blob/master/nuxt.config.js) like this:

```javascript
const dynamicRoutesPublished = getDynamicPathsPublished({
  '/content/blog/': 'content/blog/*.md',
})

...

function getDynamicPathsPublished(urlFilepathTable) {
  const stories = [].concat(
    ...Object.keys(urlFilepathTable).map(url => {
      const filepathGlob = urlFilepathTable[url];
      const routes = glob
        .sync(filepathGlob)
        .map(filepath => `${url}/${path.basename(filepath, '.md')}`);
      return routes
    })
  )
  const filtered = stories.map(story => {
     const storyName = '~'+story+'.md'
     const published = require(storyName)
     console.log(published)
  })
```

console log output is
`Cannot find module '~/content/blog/my-another-post.md'`

Trying to import the file directly
```javascript
import post from "~/content/blog/my-another-post.md"
```
also give the same output
`Cannot find module '~/content/blog/my-another-post.md'`

Is there anything wrong with my function or something I missed?

Thank you

**Comment by hmsk** [comment]
That's not the area of the loader for Webpack 😉 

You need to read md files and parse the content with Node. Probably, [front-matter module](https://www.npmjs.com/package/front-matter) helps you.
