### ISSUE TITLE
How can we enable code highlighting for markdown ?

### ISSUE THREAD

**Issue by incrypt0** [hmsk/frontmatter-markdown-loader#161]
Just got stuck on implementing code higlighting .Can I use hightlight.js for code highlighting if so How ?

I tried adding highlight to nuxt.config.js for the markdownIt key but still it is not working

**Comment by hmsk** [comment]
That depends on how you use highlight.js 🤔 
The basic usage of `highlight.js` expects `hljs.initHighlightingOnLoad();` is called after HTML is ready. So your app needs to render HTML from markdown.

Another way of highlighting code is processing with Markdown compilation. This sample is using [Prism](https://prismjs.com/) (and a plugin for markdown-it)
https://hmsk.github.io/frontmatter-markdown-loader/options.html#markdown-compilation

If you are stuck, bring a reproducible repo or an equivalent project on CodePen-ish service. I may look into then.

**Comment by incrypt0** [comment]
@hmsk  I am using nuxt js to create a personal blog that reads markdown files from a content folder.
I tried the sample with prism but it also did'nt work. If you could look into this repo It'dbe great thanks in advance :) [incrypt0/blog](https://github.com/incrypt0/blog)
