### ISSUE TITLE
Missing line breaks in code snippet

### ISSUE THREAD

**Issue by guillett** [hmsk/frontmatter-markdown-loader#166]
Many thanks for your loader :pray:!

I tried to add code snippets into some on my .md documents in a NextJS project and statically exported site. These snippets are not properly rendered. More precisely line breaks are, somehow removed and the full content get displayed on a single line.

I tried to dig into your loader and markdownIt but I got lost.
Have you ever heard about similar issue with NextJs and code snippets?
Would you have insights to share and helpp me troubleshoot that limitation?

Many thanks,

Working example:
File:
https://github.com/mes-aides/simulateur/blob/demo-break-code/contribuer/content/home.md

Render:
https://deploy-preview-48--mes-aides.netlify.app/

Project root:
https://github.com/mes-aides/simulateur/tree/demo-break-code/contribuer

(Another file:
https://github.com/mes-aides/simulateur/blob/demo-break-code/contribuer/content/tasks/ajouter-une-aide.md#v%C3%A9rifier-que-votre-environnement-est-fonctionnel---12-minutes-max

Render:
https://deploy-preview-48--mes-aides.netlify.app/tasks/ajouter-une-aide
In H2 « Préparer l'environnement de travail - 10 minutes max », H3 « Vérifier que votre environnement est fonctionnel - 12 minutes max »
)

(Plus I have a React warning, _Warning: Invalid DOM property `class`. Did you mean `className`?_ but that's may be unrelated).

**Comment by hmsk** [comment]
Thanks for bringing this to my attention! Looks it's unintentional behavior and I'm going to look into soon.

> React warning

It's fixed on v3.4.2: https://github.com/hmsk/frontmatter-markdown-loader/releases/tag/v3.4.2 😉

**Comment by hmsk** [comment]
Released a quickfix as a beta release: https://www.npmjs.com/package/frontmatter-markdown-loader/v/3.6.0-0
Could you try this?

**Comment by guillett** [comment]
Many thanks for you fast quickfix 😍!

It worked with simple situations.

However I got an error with the following file

> ---
> title: title
> ---
> 
> Some text.
> 
> ```console
> Some raw content.
> ```
> 
> With some inline code `awesome command`, it messes with the REGEX.

I saw [your quickfix](https://github.com/hmsk/frontmatter-markdown-loader/commit/f612efd811c4158780116557187dc7ab2bf3ccca#diff-168726dbe96b3ce427e7fedce31bb0bcR148-R152), I feel like you loader should rely on an HTML parser (I think I read a comment stating that you tried to avoid adding such dependency).

**Comment by hmsk** [comment]
Thanks for confirming!
Yeah, it must be the time to welcome HTML parser finally. Let me have more time for that. I'm so excited since HTML parser enables us to write more feasible codes ✨ Another beta release of v3.6.0 will come.

**Comment by hmsk** [comment]
Released v3.6.0 https://github.com/hmsk/frontmatter-markdown-loader/releases/tag/v3.6.0

Additionally, I fixed another `class` vs `className` problem and some corner cases I found in my test apps. I'm closing this PR, but happy to hear back from you whenever.
