### ISSUE TITLE
Using the dynamic example B, I am unable to render local components in markdown

### ISSUE THREAD

**Issue by tekforge** [hmsk/frontmatter-markdown-loader#176]
```html
<template>
  <div>
    <h1>{{ title }}</h1>
    <component :is="dynamicComponent" />
  </div>
</template>

<script>
import NpmOrYarn from "./NpmOrYarn.vue";

  export default {
    props: {
      filename: {
        type: String,
      },
    },
    components: {
      NpmOrYarn,
    },
    data () {
      return {
        title: null,
        dynamicComponent: null,
      }
    },
    created () {
      const markdown = require(`../md/${this.filename}`);
      this.title = markdown.attributes.title
      this.dynamicComponent = markdown.vue.component
    },
  }
</script>
```

![image](https://user-images.githubusercontent.com/61119995/85932550-83340700-b879-11ea-87d3-1cf67ff79e6e.png)

The local component isn't found by the dynamic component. In example C, the markdown component is extended to import the local components. How can the dynamic component be extended to import a component array?

**Comment by hmsk** [comment]
Need to register `NpmOrYarn` to the component which renders actually.

```js
this.dynamicComponent = {
  extends: markdown.vue.component
  components: { NpmOrYarn }
}
```

**Comment by tekforge** [comment]
@hmsk Thanks! I had tried it in dot notation, but I now see that I was trying to set a function and not an object.
