### ISSUE TITLE
Use HTML tags within markdown files?

### ISSUE THREAD

**Issue by AnthonyFromTheVault** [hmsk/frontmatter-markdown-loader#21]
This package is helping me solve the same problem you seem to have ran into, thanks so much for publishing!

I am having a bit of trouble figuring out how to use HTML tags within the markdown files. My main use case is links that contain `target="\_blank" rel="nofollow"`. I'm trying to use markdown-it as the markdown compiler and have imported with their `html: true` option, but am still seeing the full `<a>` tag being rendered in plaintext rather than a link being rendered.

sample from my nuxt.config.js:
```
let md = require('markdown-it')({
  html: true
})

build: {
    extend(config, { isDev, isClient }) {
      config.module.rules.push({
        test: /\.md$/,
        loader: 'frontmatter-markdown-loader',
        options: {
          markdown: body => {
            return md.render(body)
          }
        }
      })
    }
  }
```

**Comment by hmsk** [comment]
Seems that your component may be wrong to render the template.
I confirmed `<a>` is rendered correctly.

### Browser

![image](https://user-images.githubusercontent.com/85887/53622119-a5e2dc80-3bad-11e9-8704-834a3b1b7968.png)

### HTML

![image](https://user-images.githubusercontent.com/85887/53622134-b09d7180-3bad-11e9-9c16-7751ae265632.png)

### Markdown

![image](https://user-images.githubusercontent.com/85887/53622168-d0349a00-3bad-11e9-9816-bb7d2a66f728.png)

Btw, the rendering config is same to default, so you don't need to give that option 😉 

```js
let md = require('markdown-it')({
  html: true
})
```

https://github.com/hmsk/frontmatter-markdown-loader/blob/master/index.js#L4

I may take a look if you publish the repo to reproduce the problem 👀

**Comment by AnthonyFromTheVault** [comment]
You helped me realize that I was overthinking the configuration, and once I took out the additional options it worked completely as intended! 🙌 .

FYI for anyone else, keep the nuxt.config.js options simple if you want to use markdown-it as a parser:
```
extend(config, { isDev, isClient }) {
    config.module.rules.push({
      test: /\.md$/,
      loader: 'frontmatter-markdown-loader'
    })
}
```

**Comment by hmsk** [comment]
Glad to hear that you solved the problem.

I'm still curious about what was the exact problem in your end 🤔 

```
let md = require('markdown-it')({
  html: true
})
```

Even if we give this as the custom compilation, that should work anyways.

**Comment by AnthonyFromTheVault** [comment]
I think my problem was specifically with the webpack config I was including in my nuxt.config file: 

```
let md = require('markdown-it')

...

build: {
    extend(config, { isDev, isClient }) {
      config.module.rules.push({
        test: /\.md$/,
        loader: 'frontmatter-markdown-loader',
        options: {
          markdown: body => {
            return md.render(body)
          }
        }
      })
    }
  }
```

When I remove the `options` object, all works as intended (and my html via markdown gets properly rendered):
```
let md = require('markdown-it')

...

build: {
    extend(config, { isDev, isClient }) {
      config.module.rules.push({
        test: /\.md$/,
        loader: 'frontmatter-markdown-loader'
      })
    }
  }
```

**Comment by hmsk** [comment]
oh, so you missed `html: true` for the option of markdown-it at all?
I thought my module has bug for custom compilation since your first sample was having `html: true` which must work for inline html tags.

**Comment by AnthonyFromTheVault** [comment]
I had the `html: true` option set when I first encountered this issue, but I was also including the extra options on my webpack config which I think was my problem.

Importing markdown without the `html: true` option, and not including the options in my webpack config has everything working as expected 👍

**Comment by hmsk** [comment]
Thanks for your explanation ✨
