### ISSUE TITLE
vue: Unknown custom element from .md

### ISSUE THREAD

**Issue by gregorvoinov** [hmsk/frontmatter-markdown-loader#232]
Hi, I'm not sure what I'm doing wrong, but my vue-component doesn't get render from .md file

```html
<template>
  <vHeading lvl="1">Nice to see you.</vHeading> // <- get's rendered
  <component :is="getMarkdownComponent(section)" />
```

```javascript
<script>
  import vHeading from '@primitives/heading/heading.vue'
  import mdHeading from '@primitives/heading/docu.md'

  export default {
    extends: mdHeading.vue.component,
    components: {
      vHeading
    },
    methods: {
      getMarkdownComponent(section) {
        const md = require(`@primitives/${section}/docu.md`)
        return md.vue.component
      },
```

my markdown file

```markdown
---
subject: Hello
tags:
  - tag1
  - tag2
---
# Title
## Title

<vHeading lvl="1">Nice to see you.</vHeading> // <- doesn't get rendered

message
```

The content gets displayed, only my vue-component doesn't get rendered. I get only this error 

> "Unknown custom element:  vHeading"

**Comment by hmsk** [comment]
looks some approaches to inject an external component are mixed 👀  The Vue component which is returned by `getMarkdownComponent` didn't get `vHeadingComponent`.

There are 2 solutions to fix that:

1. Inject vHeading in the method like https://github.com/hmsk/frontmatter-markdown-loader-nuxt-sample/blob/master/pages/article.vue
2. Get rid of `<template>` block and unneeded `methods`

**Comment by hmsk** [comment]
third idea came up:

```
components: {
  MyComponent: {
    extends: vHeading,
    components: { mHeading }
  }
},
```

then use `<my-component />` on `template`

**Comment by gregorvoinov** [comment]
Hi, thanks for your help. I tried the first version and it worked ;)
