### ISSUE TITLE
Dynamic attribute.permalink possible?

### ISSUE THREAD

**Issue by regenrek** [hmsk/frontmatter-markdown-loader#34]
Hi instead of adding the url manually to frontmatter header is it possible to add the url (mostly the filename) to the attributes array? 

```
<nuxt-link to="post.attributes.permalink">{{ post.attributes.title }}</nuxt-link>
```

**Comment by hmsk** [comment]
I was thinking about this these days. The module would able to provide some metadata about the file like filename. this can't provide "permalink" technically though. That requires many contexts for the website, and that should be the out of the scope of this loader.

**Comment by regenrek** [comment]
Hey thanks for your reply. I really hoped for an suitable answer to this issue the last weeks. Since I think you should have more 'out of the box options' with this awesome library. 
You have any good suggestions to solve this problem?

**Comment by hmsk** [comment]
Thanks for your feedback.

If you have the exact idea, send PR to this repository 😉 I don't think I need to care a lot about "out of the box options". Webpack's loader system provides many ways to format original data until the importer gets. For example, you could make and add another loader to immediately before this loader to give "permalink" to frontmatter part.

But I have an idea to have meta data on the part of frontmatter attributes like

```js
import md from "markdown.md"
md.attributes._meta //=> { filename: "markdown.md", path: "/Users/whoever/...", ... }
```

So, I may add this feature, in my leisure.

**Comment by hmsk** [comment]
I added `attributes._meta.resourcePath` which reflects Webpack's loader context's `resourcePath`. To get the pathname for the markdown dynamically, you can parse that as you need.

Released as v1.7.0: https://github.com/hmsk/frontmatter-markdown-loader/releases/tag/v1.7.0

**Comment by UIX-Design** [comment]
@hmsk it is possible to add to `attributes._meta` date of creation and the date of last edited, so i can use these values for open graph protocol like this:

```js
<meta property:"article:published_time" content:"md.attributes._meta.createDate" />
<meta property:"og:updated_time" content:"md.attributes._meta.lastEditDate" />
```

**Comment by hmsk** [comment]
That's interesting. But as file-system, these dates don't show the actual time as you expect. The time is "created/modified time on the file-system".

**Comment by UIX-Design** [comment]
@hmsk ok, it is possible for you to add the „created, motified“ time to the attributes._meta array?

**Comment by hmsk** [comment]
No. I mean I'm not going to add that.
If you deploy codes to other servers (file-system), these times will be lost and show the time of the deployment.
