### ISSUE TITLE
Need more html attributes than just body

### ISSUE THREAD

**Issue by UIX-Design** [hmsk/frontmatter-markdown-loader#39]
For my project i need more parsed markdown attributes than just body. In my markdown file, i have mulitple footnotes. At the moment, a footnote consists entirely of text:

```md
---
footnotes:
     - { id: note1, title: Note 1, description: This is a new footnote }
---
```
But i need more flexibility to add html content like links, images etc. The Problem is, that i want to render the footnotes in a different place than the `body`. 

I know that i can use the `DOMParser` for that to split the `html string`, but there is no other solution that has a similar handle than the attributes?

Thanks for your help

**Comment by hmsk** [comment]
Could you give more concrete examples to explain what you'd like to? I can't get it what you mean. I'd to see actual input/output you desire. It'll be great if you propose with actual pull-request.

Or I recommend building another loader to realize your needs by yourself.

**Comment by UIX-Design** [comment]
@hmsk sure, at the moment, i parsed the footnotes array from attributes section, so i only pass strings to the object keys. I want to add multiple markdown section in the body, which i can access over dynamic variables. In principle exactly the same as with the attributes, only that I can write markdown content, such as links, pictures, videos etc:

```md
---
Titel: Post 1
Subtitle: Blog Post Number 1
---
// Page body 

# Heading 1
This is sample text

---
// access over attributes.footnote1.title
id: footnote 1
title: Footnote 1
---
// content of footnote 1
// access over attributes.footnote1.body -> rendered as html 

# Footnote 1 

This is a paragraph for footnote 1
[This is a link](https://example.com)

---
// access over attributes.footnote2.title
id: footnote 2
title: Footnote 2
---
// content of footnote 2
// access over attributes.footnote2.body -> rendered as html

# Footnote 2

This is a paragraph for footnote 2
```
Maybe so. It is important to me that I do not have to create an extra own markdown file for every footnote or any additional content. I hope you understand now what I mean...

**Comment by hmsk** [comment]
Thanks for your explanation. I didn't find the exact benefit which lets me accept to add such the complexity. The loader just focuses on importing the frontmatter-markdown file as "front matter attributes" and "compiled markdown".

> I want to add multiple markdown section in the body

I don't think that's no longer "frontmatter markdown". Front-matter attributes come to the top of the markdown **once**. If you intend to import such the file which has multiple frontmatter markdowns, I recommend you to create another Webpack loader (that may wrap this loader).

Btw, to build structural data, this doesn't work for you?

```yml
title: Title
subtitle: SubTitle
footnotes:
- id: Footnote 1
  title: first footnote
- id: Footnote 2
  title: second footnote
```

**Comment by delapuente** [comment]
@UIX-Design I suppose your case is similar to mine and you want to use Markdown for the content of the footnotes. You can give it a try to [my fork](https://github.com/delapuente/frontmatter-markdown-loader/tree/multiple) and [pass the option `multiple: true`](https://github.com/delapuente/frontmatter-markdown-loader/blob/multiple/docs/options.md#multiple-mode).

To install it, replace the `"frontmatter-markdown-loader"` entry in your `package.json` with:

```
"frontmatter-markdown-loader": "github:delapuente/frontmatter-markdown-loader#multiple"
```

Notice this version is a modification of the `master` version of the loader. A typical configuration is:

```
{
  test: /\.md$/,
  loader: 'frontmatter-markdown-loader',
  options: {
    multiple: true
  }
}

Now you can name your footnotes:

```md
---
Titel: Post 1
Subtitle: Blog Post Number 1
---
# Heading 1
This is sample text

---footnote-1
id: footnote 1
title: Footnote 1
---
# Footnote 1 

This is a paragraph for footnote 1
[This is a link](https://example.com)

---footnote-2
id: footnote 2
title: Footnote 2
---
# Footnote 2

This is a paragraph for footnote 2
```

With the multiple option enabled, you can do:

```js
import post from 'post-with-footnotes.md'
const footnotesArray = Object.keys(post.namedDocs)
.filter(key => key.startsWith('footnote'))
.map(footnoteName => post.namedDocs[footnoteName]);

footnotesArray.forEach(footnote => {
  console.log(footnote.attributes);
  console.log(footnote.html);
});
```

You can still access the post properties through `post.attributes` and `post.html`.
