### ISSUE TITLE
Vue Component doesn't work for me in NuxtJS

### ISSUE THREAD

**Issue by UIX-Design** [hmsk/frontmatter-markdown-loader#40]
I follow the Instruction to use Vue Components in my `.md` files, but it doesn't work.

my `nuxt.config.js` looks like this:

```js
const md = require('markdown-it')({ 
  html: true,
  highlight: function (str, lang) {
    if (lang && hljs.getLanguage(lang)) {
      try {
        return '<pre class="hljs"><code>' +
        hljs.highlight(lang, str, true).value +
        '</code></pre>';
      } catch (__) {}
    }
    return '<pre class="hljs"><code>' + md.utils.escapeHtml(str) + '</code></pre>';
  } 
})

config.module.rules.push({
        test: /\.md$/,
        loader: 'frontmatter-markdown-loader',
        include: path.resolve(__dirname, 'content'),
        options: {
          markdown: (body) => {
            return md.render(body)
          },  
          vue: true
        }
})
```

my markdown-file looks like this

```md
---
title: Example
subtitle: Example Markdown File with Vue Component
---
# Heading 1
This is an Paragraph

<ImageViewer>  //renders to -> <imageviewer></imageviewer>
```
my `page.vue` looks like this:

```js
<template>
     <div class="mt-8" v-html="body" />
</template>

<script>
import ImageViewer from '../../components/media/imageViewer'
import content from '../content/static/test.md'

export default {
    extends: content.vue.component,
    layout: 'static',
    components: {
        Page, ImageViewer
    },
    data() {
        return {
            body: content.html,
            title: content.attributes.title
        }
    },
}
```
Where is my mistake? I not get any issues in the dev console...

Another quick question. How can i get all `.md` files with all attributes, so i can create a dynamic blog home page with previews from all blog posts and links to each blog post? How can i do this easily in `nuxtjs` without a middleware or server?

**Comment by hmsk** [comment]
```
<template>
     <div class="mt-8" v-html="body" />
</template>
```

this looks overwriting template of the component.

> Another quick question

Technically you could. By importing markdown through this loader dynamically. That might not be straight forward since Webpack/Nuxt expects the importing is static to build static JS. However I can't help you about the specific environment.

**Comment by UIX-Design** [comment]
@hmsk thanks for your answer. When i remove the `<template>` it works now. 
But i need the following `<template>` section:

```js
<template>
    <Page :title="title" :subtitle="subtitle" :navigation="navItems != undefined" :navItems="navItems" :footnotes="footnotes">
        <div class="mt-8" v-html="body" />
    </Page>
</template>
```
So do you have an idea, how can i use this template structure with my `.md` files and vue-components inside that? I don't know how can i do that...

**Comment by hmsk** [comment]
I guess you need to have a component which loads markdown without `<template>`. Then you import and place in `pages/your-page.vue`

**Comment by UIX-Design** [comment]
@hmsk thanks for your answer. I am newcomer of Vuejs and NuxtJS. Could you give an example, so i can use your example code in my project. I think i can unterstand you better in this way - thanks
