### ISSUE TITLE
Possible to have vue-loader process images?

### ISSUE THREAD

**Issue by sustained** [hmsk/frontmatter-markdown-loader#41]
I'm using this in a Nuxt project and I was kind of hoping it would just work with [assets](https://nuxtjs.org/guide/assets/) but it doesn't.

```
![GitHub Logo](~/img/github.png)
![GitHub Logo](~assets/img/github.png)
<img src="~assets/img/github.png" />
<img src="~/img/github.png" />
```

None of these render the image, the URL is never processed.

A workaround is using the `static` folder instead of `assets` but I'd rather get assets working with this if possible!

Any thoughts or ideas?

**Comment by hmsk** [comment]
I see. Currently, the loader can't resolve the image since Markdown is compiled to HTML purely. As the request of #20, I may support html-loader for post-process of the compiled HTML and that can solve this case by giving the same config of Nuxt.

**Comment by sustained** [comment]
Sounds good!

I saw that it's possible to pass multiple loaders to Webpack via `use`. Like, right now it looks like this:

```js
      config.module.rules.push({
        test: /\.md$/,
        loader: "frontmatter-markdown-loader",
        include: resolve(__dirname, "contents"),
        options: {
          vue: {
            root: "dynamicMarkdown"
          },
          markdown: body => {
            return markdown.render(body);
          }
        }
      });
```

But after a cursory glance at the Webpack docs I saw that you can instead pass an array of loaders + options to `use`.

I wondered to myself if it might be possible to make it work that way/if it was really as simple as that? Or perhaps it is more complex and will require some work in this library. Any thoughts?

Thanks for the response and the library, by the way.

**Comment by hmsk** [comment]
Since this loader is passing the structured data (HTML is nested), can't pass that to another loader straightly. So multiple loaders don't work.

I never tried but we may intercept with `markdown` option as workaround 🤔 

```js
...
markdown: body => {
    const html = markdownCompiler.render(body);n
    // iterate image and run require("html-loader!./filename-to-assets.png"); for each
    // replace src of img with the result of ^^
    return replacedHTML;
}
...
```

anyways, I try to think about the elegant approach in my leisure. thanks.

**Comment by sustained** [comment]
Thank you, I look forward to and remain hopeful for a solution!

In the mean time I might try to hack my way around it, just for the sake of learning/experimentation.

**Comment by sustained** [comment]
FYI someone said that they had some luck chaining with `html-loader` but I had no luck when I tried it.

**Comment by hmsk** [comment]
I'm still experimenting to bypass HTML processing with html-loader. If this works, I'm going to release as beta.

And I got another idea for the workaround. You can provide the custom component which shows assets. Create the component which shows an image, then use that on markdown with like `<my-image-on-nuxt src="asset" />`.

> someone said that they had some luck chaining with html-loader

Probably, they added some tweaks. Since `frontmatter-markdown-loader` returns JSON, `html-loader` can't process straightly if chains them directly as I told in the above. (That's why I'm now exploring the decent approach)

**Comment by sustained** [comment]
I think I tried the custom component method and couldn't get it to work but I'll give it another try!

Have you had any luck with implementing this by now?

**Comment by hmsk** [comment]
I was exploring the way to make that but didn't get the appropriate approach yet.
https://github.com/hmsk/frontmatter-markdown-loader/tree/html-loader

**Comment by kutluhann** [comment]
I have the same problem. I'm waiting for you to find a solution.

**Comment by abusedmedia** [comment]
Same here that it'd be great to consider .md with its assets as a whole out of the box rather than relying with the static folder as workaround.

**Comment by hmsk** [comment]
@sustained @kutluhann @abusedmedia The pre-release of next major version `3.0.0-0` is supporting transpiling assets. It'll be helpful if anyone tries before the actual release 😉 

```
<img src="~assets/img/github.png" />
<img src="~/img/github.png" />
```

will be harmonized with `html-loader`, `file-loader` as well as `vue-loader`.
If you're using `vue.render`, `vue.staticRenderFns`, there's a breaking change: #74 

https://github.com/hmsk/frontmatter-markdown-loader/releases/tag/v3.0.0-0

**Comment by sustained** [comment]
@hmsk Sorry that I didn't get a chance to try it when it was in pre-release but I'll have a play with this now and thank you for implementing this functionality.
