### ISSUE TITLE
How to use render function directly

### ISSUE THREAD

**Issue by lukaszb** [hmsk/frontmatter-markdown-loader#49]
Hey, I've been trying to create a reusable component for all my markdown files. I have gone through https://github.com/hmsk/frontmatter-markdown-loader-vue-sample but it explains how to create a component out of a single md file. What I would like to build is something like (note this is nuxt app btw):

```vue
// ~/pages/entries/_slug/index.vue
<template>
  <div>
  <h1>{{ entry.attributes.title }}</h1>
  <MarkdownPage :entry="entry"/>
  </div>
</template>
<script>
import page1 from "~/md/page1.md"
import page2 from "~/md/page2.md"


const MarkdownPage = {
  props: ["entry"],
  created() {
    this.render = new Function(this.entry.vue.render)()
    this.$options.staticRenderFns = new Function(this.entry.vue.staticRenderFns)()
  },
}


const entries = {
  'page-1': page1,
  'page-2': page2,
}

export default {
  components: { MarkdownPage },
  async asyncData({ params }) {
    const entry = entries[params.slug]
    return {
      entry,
    }
  }
}
</script>
```

And when I try to open that page I get an error:

`render function or template not defined in component: MarkdownContent`

So I tried to define `render` function: 

```
render(createElement) {
  return this.entry.vue.component.render(createElement)
}
```

but I'm getting another error: `this.entry.vue.component.render is not a function` so I tried one more time after taking a look into [the code](https://github.com/hmsk/frontmatter-markdown-loader/blob/master/index.js#L56) but I failed at this point (not sure how should I use those `entry.vue.render` and `entry.vue. staticRenderFns` things).

Would appreciate some help here!

**Comment by hmsk** [comment]
You may miss the truncated content on https://github.com/hmsk/frontmatter-markdown-loader#vue-template (Hit `Or can take functions by compiled template as string `render`, `staticRenderFns` which are Vue component requires.`). There is the way to use `render`, `staticRenderFns`. If you don't solve with this, share your repo to reproduce. I may take a look.

**Comment by lukaszb** [comment]
omg, yes, I've totally missed that 🤦‍♂ 
Thanks a lot, worked like a charm!

**Comment by hmsk** [comment]
Happy to hear that!
