### ISSUE TITLE
Array in frontmatter is not correctly parsed

### ISSUE THREAD

**Issue by delapuente** [hmsk/frontmatter-markdown-loader#50]
Imagine I have the following frontmatter:

```md
---
- 1
- 2
- 3
---
# Markdown content
```

These attributes should be parsed as an array but due to the recently addition of the `_meta` field to the `attributes` object in 2dd5cca98037db57becc937b32bec99a5172c92c, this is no longer possible. Is this intended? Would it be possible to add the `_meta` field to the top structure? In the same way we do:

```js
md = import('something.md')
md.html
md.attributes
md.meta
```

**Comment by hmsk** [comment]
Ugh, good point. I agree with you, that's better than what I did before.
I will follow your idea. Thanks for pointing!

**Comment by delapuente** [comment]
Happy to help if you're out of bandwith. I can prepare a PR if you want.

**Comment by hmsk** [comment]
Thanks. I'm having another change that replaces the whole code structure which will conflict to the fix for this issue. So, leave this issue for me to deliver together.

**Comment by soongsta** [comment]
> Imagine I have the following frontmatter:
> 
> ```lisp
> ---
> - 1
> - 2
> - 3
> ---
> # Markdown content
> ```
> 
> These attributes should be parsed as an array but due to the recently addition of the `_meta` field to the `attributes` object in [2dd5cca](https://github.com/hmsk/frontmatter-markdown-loader/commit/2dd5cca98037db57becc937b32bec99a5172c92c), this is no longer possible. Is this intended? Would it be possible to add the `_meta` field to the top structure? In the same way we do:
> 
> ```js
> md = import('something.md')
> md.html
> md.attributes
> md.meta
> ```

I tried doing this 

      md = import(arrayitem), where arrayitem = '@/blog/post1.md'

but I am getting the following error

 Error: Cannot find module '@/blog/post1.md'

**Comment by soongsta** [comment]
hmmmm just to clarify 

`md = import(arrayitem)`

and arrayitem contains the value '@/blog/post1.md'
