### ISSUE TITLE
Vue is undefined in 2.0.0

### ISSUE THREAD

**Issue by chasebank** [hmsk/frontmatter-markdown-loader#56]
I've been trying to debug an issue with loading Markdown files in Nuxt, and have finally narrowed it down to a versioning issue for this loader.

You can test here: https://codesandbox.io/s/nuxt-markdown-blog-starter-g83c5

File attributes are successfully loaded in `/pages/index.vue` and `/pages/blog/_slug.vue`, but in the latter, `.vue` is undefined.

This seems to have broken in 2.0.0   If you change to 1.8.0 and restart the server, that fixes the problem.

**Comment by danielroe** [comment]
https://github.com/hmsk/frontmatter-markdown-loader/releases/tag/v2.0.0

**Comment by chasebank** [comment]
Awesome! Thanks for the quick reply. That does indeed fix it.
