### ISSUE TITLE
Update the README.md file

### ISSUE THREAD

**Issue by lobo-tuerto** [hmsk/frontmatter-markdown-loader#57]
Maybe add the new way to configure Webpack to have a Vue component passed down.

I was going crazy because all the tutorials show it like this:

```js
  build: {
    /*
    ** You can extend webpack config here
    */
    extend (config, ctx) {
      config.module.rules.push({
        test: /\.md$/,
        loader: 'frontmatter-markdown-loader',
        options: {
          vue: true
        }
      })
    }
  }
```

When with version 2, it's like this:

```js
import Mode from 'frontmatter-markdown-loader/mode'
// ...

  build: {
    /*
    ** You can extend webpack config here
    */
    extend (config, ctx) {
      config.module.rules.push({
        test: /\.md$/,
        loader: 'frontmatter-markdown-loader',
        // include: path.resolve(__dirname, 'content'),
        options: {
          mode: [Mode.VUE_COMPONENT]
        }
      })
    }
  }
```

I think a little example on the README.md can help to quickly identify the new way of doing it.

**Comment by hmsk** [comment]
Thanks for the feedback. I intend to remove the configuration from README.md since there was a ton of information sporadically. That's why I built [the separated documentation](https://hmsk.github.io/frontmatter-markdown-loader/).

But as your pointing, I may leave some shortcuts for the page which is talking about Vue from README.

> all the tutorials show it like this

It'll be great if you let their author know about v2 😉

**Comment by hmsk** [comment]
Tried to improve ✏️ f29767719477d399e670c79c2ce3a3634e0f8156

**Comment by lobo-tuerto** [comment]
Thank you for the updated README.md!

And about the tutorials, I think this one is yours: https://medium.com/haiiro-io/compile-front-matter-markdown-as-vue-template-9ccd55afb672 :)

**Comment by lobo-tuerto** [comment]
BTW I wrote a post on how to use [Vue.js components inside Markdown.](https://lobotuerto.com/blog/vuejs-components-inside-markdown/)

In case someone is looking for a tutorial with the v2.0. :)

**Comment by hmsk** [comment]
> And about the tutorials, I think this one is yours

😂 I must add some notes.
