### ISSUE TITLE
It's possible to use without .md file ?

### ISSUE THREAD

**Issue by hieu-brain** [hmsk/frontmatter-markdown-loader#63]
I'm using this in a Nuxt project and I want to render markdown data from Data instead of using .md file. Is it possible to do this? 
Thank you

**Comment by hmsk** [comment]
This module is just a loader for Webpack which expects to be used for import/require on JS codes. So can't support your case, unfortunately.

As the core logic is coupled with Webpack stuff, we may be able to reuse if we separate out the core logic to take markdown data and return processed JS object.
