### ISSUE TITLE
Quasar

### ISSUE THREAD

**Issue by martijnmichel** [hmsk/frontmatter-markdown-loader#84]
How would i be able to use quasar components inside md files using this loader?

When i try to use mode render:
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in render: "TypeError: Cannot read property '_c' of undefined"

When using mode component:
q-dialog is not found

I hope someone can help :)

**Comment by hmsk** [comment]
Hope you bring a reproducible repository. I never used the loader with Quasar and the error isn't enough to understand your situation.

**Comment by hmsk** [comment]
Let's reopen when a repo to repro is provided 😉
