### ISSUE TITLE
Manipulation the resulting node tree

### ISSUE THREAD

**Issue by hmsk** [hmsk/frontmatter-markdown-loader#86]
Substitute thread for @Strahinja on https://github.com/hmsk/frontmatter-markdown-loader/issues/83#issuecomment-556990107

> Current Mode.VUE_RENDER_FUNCTIONS allows manipulations on the resulting node tree, for example to highlight a search term. Is that possible with Mode.VUE_COMPONENT?

Of course. Here's the `applyHighlight` method I made:

        applyHighlight(node, h)
        {
            if (this.highlight.length>0 && node)
            {
                if (node.text)
                {
                    if (node.text.length >= this.highlight.length)
                    {
                        let result = [];
                        let i = 0;
                        let textSoFar = '';
                        while (i < node.text.length)
                        {
                            if (node.text.substring(
                                i,
                                i+this.highlight.length
                            )==this.highlight)
                            {
                                result.push(this._v(String(textSoFar)));
                                result.push(h('span', {
                                    class: 'highlight'
                                }, this.highlight));
                                textSoFar = '';
                                i += this.highlight.length;
                            }
                            else
                            {
                                textSoFar += node.text.substring(i, i+1);
                                i++;
                            }
                        }
                        if (textSoFar.length>0)
                        {
                            result.push(this._v(String(textSoFar)));
                        }
                        return result;
                    }
                }
 
                if (node.children && node.children.length>0)
                {
                    let children = [];
 
                    node.children.forEach(child =>
                    {
                        const result = this.applyHighlight(child, h);
                        if (Array.isArray(result))
                        {
                            children = children.concat(result);
                        }
                        else
                        {
                            children.push(result);
                        }
                    });
                    node.children = children;
                }
            }
            return node;
        }
    },
 
`node` is the resulting `VNode`, `h` is the function
to create them. I then just

    render (createElement)
    {
        return this.templateRender ? this.applyHighlight(this.templateRender(),
                                                         createElement) :
            createElement('div', 'Rendering...');
    }
 
Where would I search for the highlighted text with `Mode.VUE_COMPONENT`? `md.vue.component.$el`?

**Comment by hmsk** [comment]
I'm really impressed by that approach. I guess you're familiar with how Vue works 😉 (or old Vue user who needed to care about `render` function)

As you assumed, `Mode.VUE_COMPONENT` doesn't give the chance to manipulate the node tree directly, and expect to interact through `$el`.

**Comment by Strahinja** [comment]
From the documentation, `$el` is available only after mount, so the difference is that the manipulation (insertion of highlighting `<div>`s) must be done in `mounted()` instead of `render()`. I have to test more thoroughly, but that could be a breaking change. I'll post back here when I do that, hopefully during this weekend.

**Comment by hmsk** [comment]
That's a good point. So the actual timing of applying "highlight" should be different completely, hence your expectation may not be satisfied with `VUE_COMPONENT` mode 🤔

**Comment by Strahinja** [comment]
Yeah, basically I need the `FMMode.VUE_RENDER_FUNCTIONS` functionality because I use `nuxt generate`, and in addition to the above, I'm using Vuex store to handle data. My use case is [my website and blog I'm developing in Nuxt.js](https://github.com/Strahinja/strahinja-org). Is there a specific reason this feature is missing? After all, if a programmer doesn't know how to use it, they can always use `FMMode.VUE_COMPONENT`.

**Comment by hmsk** [comment]
Ah, I get it. You're generating static build of highlight-ed pages. That looks the appropriate use-case. However, I'm still aiming for the sunset of "VUE_RENDER_FUNCTIONS" to simplify the usage of FML.

Thanks for giving your repo! I will play with that since I have an idea to make it your use-case with `VUE_COMPONENT`.

**Comment by hmsk** [comment]
I tried to implement my idea and sent PR for your repo: https://github.com/Strahinja/strahinja-org/pull/1

The idea to have your highlight functionality is overwriting a component object's `render` function.

**Comment by hmsk** [comment]
@Strahinja Probably, you don't see any problem anymore...? I close this issue but feel free to reopen if you still see something worse. Thanks for sharing your use-case!

**Comment by Strahinja** [comment]
I'm sorry for not commenting here as well, I commented on the PR. Basically, the problem was to find a way to extend the loaded data. Your way of doing that solved the problem.
