### ISSUE TITLE
Getting "Cannot Import Module" errors when using Typescript

### ISSUE THREAD

**Issue by jplew** [hmsk/frontmatter-markdown-loader#88]
I was getting "Cannot Import Module" errors when attempting to import Markdown files in Typescript.

However, the solution was as simple as adding the following globals.d.ts file to my project root:

```
declare module '*.md';
```

**Comment by FDiskas** [comment]
I landed with thous types:
```ts
declare module '*.md' {
    const attributes: { [key: string]: string | string[] | {}[] };
    const react: React.FC<attributes>;
    export { attributes, react }
}
```
