### ISSUE TITLE
Nested components?

### ISSUE THREAD

**Issue by dbruning** [hmsk/frontmatter-markdown-loader#91]
If my markdown includes a component, then that component is rendered fine.
But, if that component itself includes a child component, then that child component is not rendered (just looks like a custom tag in the HTML).
Should this work? If it should work, I'll try to provide a repro. 
Thanks for this component, it's awesome!

**Comment by hmsk** [comment]
Happy to take a look :)

**Comment by dbruning** [comment]
Nevermind - this turned out to be due to a separate error which I fixed. Nested components seem to be working fine.
Thanks again!

**Comment by hmsk** [comment]
Great to hear! And thanks for [giving me a coffee](https://www.buymeacoffee.com/hmsk) ✨
